### PR TITLE
Implement Python notebook that generates TSV files about GitHub labels

### PR DESCRIPTION
**Pull request by eecavanna**
In this branch, I implemented a Python notebook that people can use to gather information about the labels that exist in the repositories in a GitHub organization, the descriptions that those labels have, and the extent to which those labels are used.

You can view the rendered version of the Python notebook [here](https://github.com/microbiomedata/issues/blob/label-management/tools/audit-github-labels.ipynb).

### CODE REVIEW

**Comment by eecavanna** [comment]
Hi @ssarrafan, I designated you as a reviewer. I don't expect you to review the code, itself. The reason I designated you as a reviewer is that I wanted to know what you thought about this repository containing code (this would be the first piece of code to reside in this repository). We can discuss this on Slack.

**Comment by ssarrafan** [comment]
> Hi @ssarrafan, I designated you as a reviewer. I don't expect you to review the code, itself. The reason I designated you as a reviewer is that I wanted to know what you thought about this repository containing code (this would be the first piece of code to reside in this repository). We can discuss this on Slack.

"Fancy Table"  Love it!  Totally ok with code in this repo.

**Review by ssarrafan — APPROVED** [review]
A ok with me

**Comment by eecavanna** [comment]
Thanks! I'll merge it in now. I didn't hear any objections on Slack from anyone either (i.e. objections to storing code in this repo).

**Pull request merged**
